/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.main;

/**
 *
 * @author bpatrocinio
 */
public class RF01 extends javax.swing.JFrame {

    /**
     * Creates new form PROTOTIPAGEM_14
     */
    public RF01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_PlanoDeFundo = new javax.swing.JPanel();
        pnl_Titulo_ListaDoArmazem = new javax.swing.JPanel();
        lbl_VoltarAoMenu = new javax.swing.JLabel();
        lbl_Titulo_ListaDoArmazem = new javax.swing.JLabel();
        pnl_Inf_ListaDoArmazen = new javax.swing.JPanel();
        lbl_CodigoDaCarga = new javax.swing.JLabel();
        txt_Categoria = new javax.swing.JTextField();
        lbl_TipoDeCarga = new javax.swing.JLabel();
        txt_CodigoDaCarga = new javax.swing.JTextField();
        lbl_Categoria = new javax.swing.JLabel();
        txt_TipoDeCarga = new javax.swing.JTextField();
        txt_Situacao = new javax.swing.JTextField();
        lbl_Situacao = new javax.swing.JLabel();
        lbl_LupaParaPesquisa = new javax.swing.JLabel();
        sln_Inf_CargasArmazenadas = new javax.swing.JScrollPane();
        tbl_TabelaDasCargasArmazenadas = new javax.swing.JTable();
        btn_Abrir_RegistroDeCarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_PlanoDeFundo.setBackground(new java.awt.Color(217, 217, 217));
        pnl_PlanoDeFundo.setPreferredSize(new java.awt.Dimension(1920, 1080));

        pnl_Titulo_ListaDoArmazem.setBackground(new java.awt.Color(36, 32, 171));
        pnl_Titulo_ListaDoArmazem.setPreferredSize(new java.awt.Dimension(1920, 100));

        lbl_VoltarAoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_VoltarAoMenuMouseClicked(evt);
            }
        });

        lbl_Titulo_ListaDoArmazem.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Titulo_ListaDoArmazem.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_Titulo_ListaDoArmazem.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Titulo_ListaDoArmazem.setText("LISTA DO ARMAZEM");

        javax.swing.GroupLayout pnl_Titulo_ListaDoArmazemLayout = new javax.swing.GroupLayout(pnl_Titulo_ListaDoArmazem);
        pnl_Titulo_ListaDoArmazem.setLayout(pnl_Titulo_ListaDoArmazemLayout);
        pnl_Titulo_ListaDoArmazemLayout.setHorizontalGroup(
            pnl_Titulo_ListaDoArmazemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Titulo_ListaDoArmazemLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_VoltarAoMenu)
                .addGap(18, 18, 18)
                .addComponent(lbl_Titulo_ListaDoArmazem)
                .addContainerGap(1519, Short.MAX_VALUE))
        );
        pnl_Titulo_ListaDoArmazemLayout.setVerticalGroup(
            pnl_Titulo_ListaDoArmazemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Titulo_ListaDoArmazemLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnl_Titulo_ListaDoArmazemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Titulo_ListaDoArmazem)
                    .addComponent(lbl_VoltarAoMenu))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnl_Inf_ListaDoArmazen.setBackground(new java.awt.Color(203, 200, 200));
        pnl_Inf_ListaDoArmazen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));

        lbl_CodigoDaCarga.setBackground(new java.awt.Color(255, 255, 255));
        lbl_CodigoDaCarga.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_CodigoDaCarga.setText("Codigo da carga");

        txt_Categoria.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbl_TipoDeCarga.setBackground(new java.awt.Color(255, 255, 255));
        lbl_TipoDeCarga.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_TipoDeCarga.setText("Tipo de carga");

        txt_CodigoDaCarga.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbl_Categoria.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Categoria.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_Categoria.setText("Categoria");

        txt_TipoDeCarga.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txt_Situacao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_Situacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SituacaoActionPerformed(evt);
            }
        });

        lbl_Situacao.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Situacao.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_Situacao.setText("Situação");

        javax.swing.GroupLayout pnl_Inf_ListaDoArmazenLayout = new javax.swing.GroupLayout(pnl_Inf_ListaDoArmazen);
        pnl_Inf_ListaDoArmazen.setLayout(pnl_Inf_ListaDoArmazenLayout);
        pnl_Inf_ListaDoArmazenLayout.setHorizontalGroup(
            pnl_Inf_ListaDoArmazenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Inf_ListaDoArmazenLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnl_Inf_ListaDoArmazenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_CodigoDaCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_CodigoDaCarga))
                .addGap(61, 61, 61)
                .addGroup(pnl_Inf_ListaDoArmazenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Categoria)
                    .addComponent(lbl_Categoria, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addGroup(pnl_Inf_ListaDoArmazenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TipoDeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TipoDeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(pnl_Inf_ListaDoArmazenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Situacao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_Inf_ListaDoArmazenLayout.createSequentialGroup()
                        .addComponent(txt_Situacao, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lbl_LupaParaPesquisa)))
                .addContainerGap(662, Short.MAX_VALUE))
        );
        pnl_Inf_ListaDoArmazenLayout.setVerticalGroup(
            pnl_Inf_ListaDoArmazenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Inf_ListaDoArmazenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Inf_ListaDoArmazenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_LupaParaPesquisa)
                    .addGroup(pnl_Inf_ListaDoArmazenLayout.createSequentialGroup()
                        .addGroup(pnl_Inf_ListaDoArmazenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_TipoDeCarga, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_Inf_ListaDoArmazenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_CodigoDaCarga)
                                .addComponent(lbl_Categoria)
                                .addComponent(lbl_Situacao)))
                        .addGap(17, 17, 17)
                        .addGroup(pnl_Inf_ListaDoArmazenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_CodigoDaCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TipoDeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Situacao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tbl_TabelaDasCargasArmazenadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_TabelaDasCargasArmazenadas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbl_TabelaDasCargasArmazenadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código da carga", "Produto", "Categoria", "Quatindade / Uni", "Tipo de carga", "Situação", "Localização"
            }
        ));
        tbl_TabelaDasCargasArmazenadas.setGridColor(new java.awt.Color(0, 0, 0));
        tbl_TabelaDasCargasArmazenadas.setMaximumSize(new java.awt.Dimension(1900, 1000));
        tbl_TabelaDasCargasArmazenadas.setPreferredSize(new java.awt.Dimension(1900, 1000));
        tbl_TabelaDasCargasArmazenadas.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tbl_TabelaDasCargasArmazenadas.setShowGrid(true);
        sln_Inf_CargasArmazenadas.setViewportView(tbl_TabelaDasCargasArmazenadas);

        btn_Abrir_RegistroDeCarga.setBackground(new java.awt.Color(32, 41, 173));
        btn_Abrir_RegistroDeCarga.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        btn_Abrir_RegistroDeCarga.setForeground(new java.awt.Color(255, 255, 255));
        btn_Abrir_RegistroDeCarga.setText("Abrir");
        btn_Abrir_RegistroDeCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Abrir_RegistroDeCargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_PlanoDeFundoLayout = new javax.swing.GroupLayout(pnl_PlanoDeFundo);
        pnl_PlanoDeFundo.setLayout(pnl_PlanoDeFundoLayout);
        pnl_PlanoDeFundoLayout.setHorizontalGroup(
            pnl_PlanoDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PlanoDeFundoLayout.createSequentialGroup()
                .addComponent(pnl_Titulo_ListaDoArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnl_PlanoDeFundoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnl_PlanoDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sln_Inf_CargasArmazenadas)
                    .addComponent(pnl_Inf_ListaDoArmazen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PlanoDeFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Abrir_RegistroDeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        pnl_PlanoDeFundoLayout.setVerticalGroup(
            pnl_PlanoDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PlanoDeFundoLayout.createSequentialGroup()
                .addComponent(pnl_Titulo_ListaDoArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_Inf_ListaDoArmazen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sln_Inf_CargasArmazenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Abrir_RegistroDeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_PlanoDeFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_PlanoDeFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_SituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SituacaoActionPerformed

    private void lbl_VoltarAoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VoltarAoMenuMouseClicked
        // TODO add your handling code here:
        RF30 MenuPrincipal = new RF30();
        MenuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_VoltarAoMenuMouseClicked

    private void btn_Abrir_RegistroDeCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Abrir_RegistroDeCargaActionPerformed
        // TODO add your handling code here:
        RF15 RegistroDeCarga = new RF15();
        RegistroDeCarga.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Abrir_RegistroDeCargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RF01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RF01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RF01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RF01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RF01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Abrir_RegistroDeCarga;
    private javax.swing.JLabel lbl_Categoria;
    private javax.swing.JLabel lbl_CodigoDaCarga;
    private javax.swing.JLabel lbl_LupaParaPesquisa;
    private javax.swing.JLabel lbl_Situacao;
    private javax.swing.JLabel lbl_TipoDeCarga;
    private javax.swing.JLabel lbl_Titulo_ListaDoArmazem;
    private javax.swing.JLabel lbl_VoltarAoMenu;
    private javax.swing.JPanel pnl_Inf_ListaDoArmazen;
    private javax.swing.JPanel pnl_PlanoDeFundo;
    private javax.swing.JPanel pnl_Titulo_ListaDoArmazem;
    private javax.swing.JScrollPane sln_Inf_CargasArmazenadas;
    private javax.swing.JTable tbl_TabelaDasCargasArmazenadas;
    private javax.swing.JTextField txt_Categoria;
    private javax.swing.JTextField txt_CodigoDaCarga;
    private javax.swing.JTextField txt_Situacao;
    private javax.swing.JTextField txt_TipoDeCarga;
    // End of variables declaration//GEN-END:variables
}
