/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pmedeiros
 */
public class RF23 extends javax.swing.JFrame {

    /**
     * Creates new form RF23
     */
    RF25 enviaquantidade;
    int valor = 0;
    int codigo;
    int etiqueta = 0;

    public RF23() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_principal = new javax.swing.JPanel();
        Pnl_barraAzul = new javax.swing.JPanel();
        Lbl_localização = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lbl_quantidade = new javax.swing.JLabel();
        Lbl_rua = new javax.swing.JLabel();
        Lbl_pilha = new javax.swing.JLabel();
        Lbl_corredor = new javax.swing.JLabel();
        Lbl_nivel = new javax.swing.JLabel();
        Tfd_quantidade = new javax.swing.JTextField();
        Tfd_pilha = new javax.swing.JTextField();
        Tfd_rua = new javax.swing.JTextField();
        Tfd_corredor = new javax.swing.JTextField();
        Tfd_nivel = new javax.swing.JTextField();
        Btn_salvar = new javax.swing.JButton();
        Lbl_contagem = new javax.swing.JLabel();
        txt_quantidade = new javax.swing.JTextField();
        txt_cod = new javax.swing.JTextField();
        txt_recebeEndereco = new javax.swing.JTextField();
        Btn_salvar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pnl_principal.setBackground(new java.awt.Color(203, 200, 200));

        Pnl_barraAzul.setBackground(new java.awt.Color(32, 41, 173));

        Lbl_localização.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_localização.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lbl_localização.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_localização.setText("LOCALIZAÇÃO");

        jLabel2.setIcon(new javax.swing.ImageIcon("P:\\TURMAS\\HTC-DDS-16\\ícones WMS\\icon_back.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pnl_barraAzulLayout = new javax.swing.GroupLayout(Pnl_barraAzul);
        Pnl_barraAzul.setLayout(Pnl_barraAzulLayout);
        Pnl_barraAzulLayout.setHorizontalGroup(
            Pnl_barraAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_barraAzulLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(Lbl_localização)
                .addContainerGap(423, Short.MAX_VALUE))
        );
        Pnl_barraAzulLayout.setVerticalGroup(
            Pnl_barraAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_barraAzulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl_barraAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pnl_barraAzulLayout.createSequentialGroup()
                        .addComponent(Lbl_localização)
                        .addGap(9, 9, 9))
                    .addComponent(jLabel2))
                .addGap(19, 19, 19))
        );

        Lbl_quantidade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lbl_quantidade.setText("Quantidade");

        Lbl_rua.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lbl_rua.setText("Rua");

        Lbl_pilha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lbl_pilha.setText("Pilha");

        Lbl_corredor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lbl_corredor.setText("Corredor");

        Lbl_nivel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lbl_nivel.setText("Nivel");

        Btn_salvar.setBackground(new java.awt.Color(32, 41, 173));
        Btn_salvar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Btn_salvar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_salvar.setText("Salvar");
        Btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_salvarActionPerformed(evt);
            }
        });

        Lbl_contagem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lbl_contagem.setText("Contagem : ");

        txt_recebeEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_recebeEnderecoActionPerformed(evt);
            }
        });

        Btn_salvar1.setBackground(new java.awt.Color(32, 41, 173));
        Btn_salvar1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Btn_salvar1.setForeground(new java.awt.Color(255, 255, 255));
        Btn_salvar1.setText("Salvar");
        Btn_salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_salvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_principalLayout = new javax.swing.GroupLayout(Pnl_principal);
        Pnl_principal.setLayout(Pnl_principalLayout);
        Pnl_principalLayout.setHorizontalGroup(
            Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_barraAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Pnl_principalLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Pnl_principalLayout.createSequentialGroup()
                        .addComponent(Lbl_quantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tfd_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(Lbl_contagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_quantidade))
                    .addGroup(Pnl_principalLayout.createSequentialGroup()
                        .addGroup(Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Pnl_principalLayout.createSequentialGroup()
                                .addComponent(Lbl_rua)
                                .addGap(18, 18, 18)
                                .addComponent(Tfd_rua))
                            .addGroup(Pnl_principalLayout.createSequentialGroup()
                                .addComponent(Lbl_pilha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tfd_pilha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_corredor)
                            .addComponent(Lbl_nivel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tfd_corredor)
                            .addGroup(Pnl_principalLayout.createSequentialGroup()
                                .addComponent(Tfd_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_principalLayout.createSequentialGroup()
                        .addComponent(txt_recebeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(Btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_principalLayout.createSequentialGroup()
                    .addContainerGap(475, Short.MAX_VALUE)
                    .addComponent(Btn_salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(59, 59, 59)))
        );
        Pnl_principalLayout.setVerticalGroup(
            Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_principalLayout.createSequentialGroup()
                .addComponent(Pnl_barraAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_quantidade)
                    .addComponent(Tfd_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_contagem)
                    .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_rua)
                    .addComponent(Lbl_corredor)
                    .addComponent(Tfd_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfd_corredor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_pilha)
                    .addComponent(Lbl_nivel)
                    .addComponent(Tfd_pilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfd_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_principalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_recebeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(Pnl_principalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Btn_salvar)
                        .addContainerGap(34, Short.MAX_VALUE))))
            .addGroup(Pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_principalLayout.createSequentialGroup()
                    .addContainerGap(341, Short.MAX_VALUE)
                    .addComponent(Btn_salvar1)
                    .addGap(4, 4, 4)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void PopularEnreco(String sql){
        
        try {
            String url = "jdbc:mysql://10.145.41.252:3306/DB_WMS_PRD";
            String usuario = "dds16_wms";
            String senha = "";
            String chave = sql;
            
            Connection con = DriverManager.getConnection(url,usuario,senha);
            
            PreparedStatement ps = con.prepareStatement(chave);
            
            Statement st =  con.createStatement();
            ResultSet resultado = st.executeQuery(chave);
            
            //ResultSet resultado = st.executeQuery();
            
            while (resultado.next()){
                txt_recebeEndereco.setText(resultado.getString("id"));
            }
            
            st.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage()); 
            //Logger.getLogger(RF23.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    private void Btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_salvarActionPerformed
          
        int quantidade = Integer.parseInt(Tfd_quantidade.getText());
        try{   
            
        
        if(quantidade > valor || quantidade < 0){
            JOptionPane.showMessageDialog(rootPane, "Valor inserido incorreto");
        }    
        else{
            
            
            String url = "jdbc:mysql://10.145.41.252:3306/DB_WMS_PRD";
            String usuario = "dds16_wms";
            String senha = "";
            
            Connection conn = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement statement;
            
            String Endereco; 
            Endereco = ((Tfd_rua.getText()) + "." + (Tfd_corredor.getText()) + "." + (Tfd_pilha.getText()) + "." + (Tfd_nivel.getText())) ;
            
            this.PopularEnreco(" SELECT * FROM enderecos WHERE endereco = "+Endereco);
            
            statement = conn.prepareStatement("INSERT INTO cargas (quantidade, rua, pilha, corredor, nivel, etiqueta,endereco_id,agendamento_id) VALUES (?,?,?,?,?,?,?,?)");         
            
            //String etiqueta = ("ET-N-"+);
            
            
            
            statement.setString(1,Tfd_quantidade.getText());
            statement.setString(2,Tfd_rua.getText());        
            statement.setString(3,Tfd_pilha.getText());
            statement.setString(4,Tfd_corredor.getText());
            statement.setString(5,Tfd_nivel.getText());
            statement.setString(6, "ET-N-"+etiqueta);
            statement.setString(7,txt_recebeEndereco.getText());
            statement.setString(8,txt_cod.getText());
            
            //WHERE id = ? statement.setInt(6, codigo);

            statement.execute();
            statement.close();
            
            JOptionPane.showMessageDialog(rootPane, "Local selecionado");        
            
                      
            valor = valor - quantidade;
            enviaquantidade = new RF25();
            enviaquantidade.setVisible(true);
            enviaquantidade.etiqueta(valor);
            this.dispose();
        }
        
     }catch(SQLException ex){  
         Logger.getLogger(RF18.class.getName()).log(Level.SEVERE, null, ex);             
     }
        
        

	
        

        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_salvarActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
   RF18 recebimento  = new RF18();
        recebimento.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_recebeEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_recebeEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_recebeEnderecoActionPerformed

    private void Btn_salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_salvar1ActionPerformed

        try {
            String Endereco;
            Endereco = (Tfd_rua.getText() + "." + Tfd_corredor.getText() + "." + Tfd_pilha.getText() + "." + Tfd_nivel.getText()) ;
            
            System.out.println(Endereco);
            String chave = ("SELECT * FROM enderecos WHERE rua ="+"P");//Endereco);
            
            String url = "jdbc:mysql://10.145.41.252:3306/DB_WMS_PRD";
            String usuario = "dds16_wms";
            String senha = "";
 
            Connection con = DriverManager.getConnection(url,usuario,senha);
            
            PreparedStatement ps = con.prepareStatement(chave);
            
            Statement st =  con.createStatement();
            ResultSet resultado = st.executeQuery(chave);
            
            //ResultSet resultado = st.executeQuery();
            
            while (resultado.next()){
                txt_recebeEndereco.setText(resultado.getString("id"));
            }
            
            st.close();
            con.close();
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(RF23.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_salvar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RF23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RF23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RF23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RF23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RF23().setVisible(true);
            }
        });
    }
    
    public void recebendo(String a){
        txt_quantidade.setText(a);
        valor = Integer.parseInt(a);
        //codigo = Integer.parseInt(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_salvar;
    private javax.swing.JButton Btn_salvar1;
    private javax.swing.JLabel Lbl_contagem;
    private javax.swing.JLabel Lbl_corredor;
    private javax.swing.JLabel Lbl_localização;
    private javax.swing.JLabel Lbl_nivel;
    private javax.swing.JLabel Lbl_pilha;
    private javax.swing.JLabel Lbl_quantidade;
    private javax.swing.JLabel Lbl_rua;
    private javax.swing.JPanel Pnl_barraAzul;
    private javax.swing.JPanel Pnl_principal;
    private javax.swing.JTextField Tfd_corredor;
    private javax.swing.JTextField Tfd_nivel;
    private javax.swing.JTextField Tfd_pilha;
    private javax.swing.JTextField Tfd_quantidade;
    private javax.swing.JTextField Tfd_rua;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_cod;
    private javax.swing.JTextField txt_quantidade;
    private javax.swing.JTextField txt_recebeEndereco;
    // End of variables declaration//GEN-END:variables
void etiqueta(String text_a) {
      txt_cod.setText(text_a);
      
      etiqueta = Integer.parseInt(text_a);

}
}
     
    
